#include "tlpp-i18n.th"

/* ==========================================================================
   DOC: /init/dyn | Método: GET
   ========================================================================== */
function U_FUNC_DYN_GET_DOC() as character

    local cJson := '' as character

    TOSTRING cJson#;
    { ;
        "title" : "Exemplo 01 dinâmico", ;
        "description" : "Documentação do endpoint [/init/dyn] método [GET] gerado dinamicamente sem annotation.", ;
        "responses" : [ ;
            { ;
                "statusCode" : 200, ;
                "description" : "Sucesso | Content: [FUNC_DYN hh:mm:ss]" ;
            } ;
        ] ;
    }

return cJson

/* ==========================================================================
   DOC: /init/dyn | Método: PUT
   ========================================================================== */
function U_FUNC_DYN_PUT_DOC() as character

    local cJson := '' as character

    TOSTRING cJson#;
    { ;
        "title" : "Exemplo 02 dinâmico", ;
        "description" : "Documentação do endpoint [/init/dyn] método [PUT] gerado dinamicamente sem annotation.", ;
        "responses" : [ ;
            { ;
                "statusCode" : 200, ;
                "description" : "Sucesso | Content: [FUNC_DYN hh:mm:ss]" ;
            } ;
        ] ;
    }

return cJson

/* ==========================================================================
   DOC: /class/:param1 | Método: GET
   ========================================================================== */
function U_CLASS_DYN_GET_DOC() as character

    local cJson := '' as character

    TOSTRING cJson#;
    { ;
        "title" : "Exemplo 03 dinâmico", ;
        "description" : "Documentação do endpoint [/class/:param1] método [GET] gerado dinamicamente sem annotation e recebendo 1 PathParam.", ;
        "params" : [ ;
            { ;
                "name" : "param1", ;
                "description" : "Parâmetro param1 recebido via Path Param.", ;
                "in" : "path", ;
                "required" : true, ;
                "type" : "character" ;
            } ;
        ], ;
        "responses" : [ ;
            { ;
                "statusCode" : 200, ;
                "description" : "Sucesso | Content: [METHOD_DYN hh:mm:ss [{param1:value_param}]]" ;
            } ;
        ] ;
    }

return cJson
